# -*- coding: utf-8 -*-
"""Day4 task1.2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RT-f74hlbvT5wdTU9WK0g48FohqpMv0v
"""

import pandas as pd

df = pd.read_csv("/content/insurance.csv")
df.head()

from sklearn.preprocessing import LabelEncoder
# Encoding
LE = LabelEncoder()
features = ['sex', 'smoker']

for f in features:
    df[f] = LE.fit_transform(df[f])

df.loc[:10, ['sex', 'smoker']]

df = df.drop('region',axis =1)
df

Y = df.charges
X = df.drop('charges', axis =1)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=44, shuffle =True)

#Splitted Data
print('X_train shape is ' , X_train.shape)
print('X_test shape is ' , X_test.shape)
print('y_train shape is ' , y_train.shape)
print('y_test shape is ' , y_test.shape)

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error


#Applying Random Forest Regressor Model
RandomForestRegressorModel = RandomForestRegressor(n_estimators=100,max_depth=2, random_state=33)
RandomForestRegressorModel.fit(X_train, y_train)
y_pred = RandomForestRegressorModel.predict(X_test)
mse = mean_squared_error(y_test, y_pred)

#Calculating Details
print('Random Forest Regressor Train Score is : ' , RandomForestRegressorModel.score(X_train, y_train))
print('Random Forest Regressor Test Score is : ' , RandomForestRegressorModel.score(X_test, y_test))
print(f'Random Forest Regressor Test MSE is : {mse}')

from sklearn.linear_model import LinearRegression

LinearRegressionModel = LinearRegression()
LinearRegressionModel.fit(X_train, y_train)
y_pred = LinearRegressionModel.predict(X_test)
mse = mean_squared_error(y_test, y_pred)

print('Linear Regression Train Score is : ', LinearRegressionModel.score(X_train, y_train))
print('Linear Regression Test Score is : ', LinearRegressionModel.score(X_test, y_test))
print(f'Linear Regression Test MSE is : {mse}')